version: '2.4'

services:
  auroral-agent:
    container_name: auroral-agent
    image: auroral-agent
    volumes:
    - ./.env:/app/.env:ro
    - .:/app:delegated
    depends_on:
      cache-db:
        condition: service_healthy
  proxy:
    container_name: proxy
    volumes:
    - ./nginx/logs:/var/log/nginx
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # - /etc/ssl/bavenir/bavenir_eu.key:/var/certificates/privkey.pem:ro
    # - /etc/ssl/bavenir/bavenir_eu.crt:/var/certificates/fullchain.pem:ro
    depends_on:
      cache-db:
        condition: service_healthy
    ports:
      - 9997:9997
      - 81:80
      # - 443:443
    image: nginx:stable
  gateway:
    container_name: gateway
    # restart: always
    volumes:
    - ./gateway/log:/gateway/log
    - ./gateway/GatewayConfig.xml:/gateway/config/GatewayConfig.xml:ro
    - ./gateway/keystore:/gateway/keystore
    environment:
    - UID=9999
    - GID=9999
    # ports:
    # - 8181:8181
    # image: registry.bavenir.eu/auroral_gateway:dev
    image: auroral-gateway
  cache-db:
    container_name: cache-db
    # restart: always
    # ports:
    # - 6379:6379
    volumes:
    - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    - ./redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    command:
    - /usr/local/etc/redis/redis.conf
    image: redis:buster